import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UnifrakturMaguntia, Archivo_Black } from "next/font/google";

const unifraktur = UnifrakturMaguntia({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-unifraktur",
});

const archivo = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-archivo",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${unifraktur.variable} ${archivo.variable}${geistSans.variable}${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
